import React from 'react'
import PublicNavigationMenu from '../components/this-website-only/navigation-menu/desktop/PublicNavigationMenu'
import PublicFooter from '../components/this-website-only/footer/PublicFooter'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Love Transfusion',
  // description: 'Generated by create next app',
}

const LayoutForPagesWithNavigationMenu = ({
  children,
}: {
  children: React.ReactNode
}) => {
  return (
    <>
      <PublicNavigationMenu />
      <div className={'border-4 border-r-0 border-[#B0E0F1]'}>{children}</div>
      <PublicFooter />
    </>
  )
}

export default LayoutForPagesWithNavigationMenu
