import type { Metadata } from 'next'
import './globals.css'
import GlobalToast from './GlobalToast'

export const revalidate = 30

export const metadata: Metadata = {
  title: 'Love Transfusion',
  // description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/hox1ite.css" />
      </head>
      <body className="font-acumin-variable">
        <GlobalToast />
        <div>{children}</div>
      </body>
    </html>
  )
}
