// ✅ List of banned keywords, phrases, or emojis (lowercase only)
export const BANNED_KEYWORDS = [
  'c24/7','plexus','truth','died','#fuckcancer','business','ketogenic','diet','bruzunski\'s','bruzunski',
  'cantron','protocel','qure','nigger','shyt','fucka','droz','oz','race','aborted','abort','abortion',
  'fucking','whore','starbucks','fukashima','mercury','c0stc0','costco','organic','dandelion','burzynski',
  'marijuana','cannibis','cannabis','canabis','bryzinski','shit','fuck','damn','bitch','hell','cock','hemp',
  'dick','crap','bullshit','dumb','stupid','idiot','alkaline','vinager','vinegar','asshole','arsehole',
  'medolife','motherfucker','dickass','asswholes','phoenix','burzinski','coldwell','gerson',
  'orgone accumulators','hunter','cunt','fuk','graviola','chong','bieber','gomez','majors','laminine','fake',
  'scam','ugly','loser','pathetic','cringe','annoying','dm for promo','promote it on','collab','message us',
  'check my page','crypto','forex','send your post to','nudes','follow me','check out my profile','feature',
  'sex','sexy','naked','hot pics','onlyfans','explicit','dm me','prophet','psychic','porn','passed','dead',
  'killed','killer','murder','murdered','😂','🤣','black','negro','naturopathic','herbalist','victim','dm',
  'ivermectin','parasite','congrats','congratulations','arthritis','cleanse','natural','herb','herbs','iv',
  'intraveneous','intravenous','nicotine','dr','protocol','fenbendazol','dog','🤣😂','hormone','butt',
  'sulforaphane','mebendazole','soursop','wormwood','worm wood','heroine','meth','drug','weight','images',
  'fat','lame','lost','sad','success','passed away','ass','research','😛','😝','🤪','🤬','😜','😈','👿','👹',
  '👺','🤡','💩','👻','💀','☠️','😹','🖕','😋','fenbendazole','rapist','democrat','republic','raping','friend',
  'friend request','chemical','chemicals','poison','poisoned','gaza','republican','republicans','demonrat',
  'trump','israel','zion','🦛','🦍','🦧','altered','singled','fck','kernel','blue','illegal','alien',
  'immigrant','migrant','fasting','anus','anal','arse','ballsack','balls','bastard','biatch','bloody',
  'blowjob','blow job','bollock','bollok','boner','boob','bugger','bum','buttplug','clitoris','coon','dildo',
  'dyke','fag','feck','fellate','fellatio','felching','f u c k','fudgepacker','fudge','packer','goddamn',
  'homo','jerk','jizz','knobend','knob','labia','lmao','lmfao','muff','nigga','omg','penis','piss','poop',
  'prick','pube','scrotum','s hit','sh1t','slut','smegma','spunk','tit','tits','tosser','turd','twat',
  'vagina','wank','wtf','wth','puta','gilipollas','cabrón','mierda','coño','puta madre','jodete','idiota',
  'joder','gonorrea','jodido','chichis','pinga','cabróna','pendejo','pendeja','carajo','queer','concha',
  'puto','boludo','boluda','cono','verga','chingado','chingada','pinche','culiao','chucha','malparido',
  'marica','demonios','diablo','screw','screwed','drink','smoke','jab','lick','licker','liquor','wipe',
  'clown','douche','retard','fagtard','faggit','fuckin','fatass','goddamnit','gook','gooch','hump','hoe',
  'heeb','chink','honkey','jigaboo','jungle','jagoff','kyke','kike','kootch','lameass','lardass','lesbian',
  'lesbo','lezzie','masturbate','mothafucka','nazi','nut','nuts','pecker','pissed','pollock','poon','punta',
  'pussies','pussy','sand','scrote','shitty','shiz','skank','skeet','spic','spick','spook','suck','tard',
  'testicle','twit','wop','cazzo','stronzo','merda','merde','putain','loonie','hoser','fick','genital',
  'herpes','std','wart','remedy','remedies','medication','medicine','metastases','metastatic','lymph','ph',
  'process','democrats','deworm','worm','detox','request','profile','sucks','donate','donates','requests',
  'profiles','medications','meds','med','doc','docs','worms','hates','hate','bald','immigrants','illegals',
  'migrants','demoncrat','demoncrats','demonrats','zionism','trumps','isreals','poisons','pass','passes',
  'parasites','die','dies','chemo','radiation','fen ben','money','grape','seed','extract','rent','elon',
  'musk','vance','starve','manuka','live','okundo','hub','lol','oil','vaccine','vaccines','oils','isreal',
  'palestine','hepatitis','aids','jude','chimio','lying','rump',
]
